name: SpeedEdit
main: ca.fastis.SpeedEdit
version: 2.0
author: _Auracle_
api-version: 1.14
softdepend: [CoreProtect]
website: https://github.com/VirgilFabre
commands:
   set:
      description: 
      usage: /<command> [Material]
   replace:
      description: 
      usage: /<command> [Material] [Material]
   hammer:
      description: 
      usage: /<command>
   pos1:
      description: 
      usage: /<command>
   pos2:
      description: 
      usage: /<command>
   undo:
      description: 
      usage: /<command>
   redo:
      description: 
      usage: /<command>
   copy:
      description: 
      usage: /<command>
   paste:
      description: 
      usage: /<command>
   expand:
      description: 
      usage: /<command> [Amount] [Direction]
   move:
      description: 
      usage: /<command> [Amount] [Direction]
   walls:
      description: 
      usage: /<command> [Material]
   outline:
      description: 
      usage: /<command> [Material]
   skeleton:
      description: 
      usage: /<command> [Material]
   log:
      description: 
      usage: /<command>
   speededit:
      description: 
      usage: /<command>