name: SpeedEdit
main: ca.fastis.SpeedEdit
version: 1.0
author: SellerSkyblock
api-version: 1.14
commands:
   set:
      permission: speededit.set
      description: 
      usage: /<command> {Material}
   hammer:
      permission: speededit.hammer
      description: 
      usage: /<command>
   pos1:
      permission: speededit.use
      description: 
      usage: /<command>
   pos2:
      permission: speededit.use
      description: 
      usage: /<command>