name: SpeedEdit
main: auracle.SpeedEdit
version: 2.1
author: Hausemestar
api-version: 1.14
softdepend: [CoreProtect]
website: https://github.com/AuracleTech
commands:
   set:
      description: Set blocks to a material
      usage: /<command> [Material]
   replace:
      description: Replace blocks from a material to another material
      usage: /<command> [Material] [Material]
   hammer:
      description: Gift the SpeedEdit Hammer
      usage: /<command>
   pos1:
      description: Set the first SpeedEdit position
      usage: /<command>
   pos2:
      description: Set the second SpeedEdit position
      usage: /<command>
   undo:
      description: Undo a SpeedEdit command
      usage: /<command>
   redo:
      description: Redo a SpeedEdit command
      usage: /<command>
   copy:
      description: Copy a SpeedEdit zone in the clipboard
      usage: /<command>
   paste:
      description: Paste a SpeedEdit zone from the clipboard
      usage: /<command>
   expand:
      description: Expand a SpeedEdit selected zone
      usage: /<command> [Amount]
   move:
      description: Move the SpeedEdit selected zone
      usage: /<command> [Amount]
   walls:
      description: Creates a wall of the selected SpeedEdit zone
      usage: /<command> [Material]
   outline:
      description: Creates an outline of the selected SpeedEdit zone
      usage: /<command> [Material]
   skeleton:
      description: Creates a of the selected SpeedEdit zone
      usage: /<command> [Material]
   sphere:
      description: Generate a sphere from the player position
      usage: /<command> [Material] [Radius]
   hsphere:
      description: Generate a hollow sphere from the player position
      usage: /<command> [Material] [Radius]
   log:
      description: CoreProtect cooperation - Register the selected SpeedEdit zone to CoreProtect
      usage: /<command>
   speededit:
      description: Give all informations about SpeedEdit
      usage: /<command>